/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_object_to_xml;

import java.util.Arrays;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

import java_object_to_xml.model.FmtLmt;
import java_object_to_xml.model.PbLimit;
import java_object_to_xml.model.ServiceBody;
import java_object_to_xml.model.ServiceEnvelop;
import java_object_to_xml.model.ServiceHeader;

public class App {
  public static void main(String[] args) throws JAXBException {
    JAXBContext jaxbContext = JAXBContext.newInstance(ServiceEnvelop.class);
    ServiceEnvelop serviceEnvelop = new ServiceEnvelop();
    ServiceHeader serviceHeader = new ServiceHeader();
    ServiceBody serviceBody = new ServiceBody();
    PbLimit pbLimit = new PbLimit();
    
    serviceHeader.setVersion("1.0");
    serviceHeader.setServiceName("TestName");
    serviceHeader.setServiceProvider("TestProvider");

    pbLimit.setCustPermId("1234");
    pbLimit.setCountryCode("TW");
    pbLimit.setLineCode("test");
    pbLimit.setMainLineCode("mainTest");
    pbLimit.setFmtLmt(Arrays.asList(new FmtLmt("testCcy1", "230000"), new FmtLmt("testCcy2", "300000")));

    serviceBody.setPbLimit(pbLimit);

    serviceEnvelop.setServiceHeader(serviceHeader);
    serviceEnvelop.setServiceBody(serviceBody);

    Marshaller marshaller = jaxbContext.createMarshaller();
    marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
    marshaller.marshal(serviceEnvelop, System.out);
  }
}
